name: sst1m-dev
channels:
  - conda-forge
  - default
dependencies:
  - python==3.11
  - pip
  - coverage
  - ctapipe==0.21.2
  - click
  - gammapy==1.3
  - h5py
  - jupyter
  - protozfits # used to read zfits files and protocolbuffer messages
  - astroquery=0.4.6
  - matplotlib
  - nbmake # used to pytest jupyter notebooks
  - pytables # to read hdf5 tables
  - pytest
  - ruff
  - setuptools<81 # required for ctapipe 0.17
  - scikit-learn
  - scipy
  - sphinx
  - sphinx-automodapi
  - sphinx-argparse
  - sphinx-design
  - sphinx_rtd_theme
  - sphinx-togglebutton
  - sphinxcontrib-mermaid
  - nbsphinx
  - numpydoc
  - wheel
  - pip:
      - ctaplot~=0.6.2
      - pyirf~=0.8.0
      - cts @ git+https://github.com/SST-1M-collaboration/CTS.git
