name: sst1m-dev
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - pip
  - ctapipe=0.30
  - gammapy=2.1
  - jupyter
  - protozfits=2.11
  - astroquery=0.4.11
  - pytest
  - ruff
  - sphinx
  - sphinx-automodapi
  - sphinx-design
  - sphinx_rtd_theme
  - numpydoc
  - pip:
      - ctaplot~=0.6.5
      - pyirf~=0.13.0
      - git+https://github.com/SST-1M-collaboration/CTS.git
