name: documentation

on: [pull_request]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Micromamba env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          generate-run-shell: true
          post-cleanup: 'all'
      - name: Pip install source
        shell: micromamba-shell {0}
        run: pip install .
      - name: Sphinx build
        shell: micromamba-shell {0}
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
      - name: Deploy on readthedocs
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: "readthedocs-preview"